AllCops:
  Exclude:
    - 'bin/bundle'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 60

Layout/LineLength:
  Max: 120

Naming/VariableNumber:
  Enabled: false

Metrics/BlockNesting:
  Max: 4

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/ParameterLists:
  Max: 5

Metrics/PerceivedComplexity:
  Max: 17

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'components/**/spec/**/*.rb'
    - 'config/routes.rb'
    - 'app/lib/app_config.rb'